// SPDX-License-Identifier: Apache-2.0
// The Ajar event contract is licensed Apache-2.0 — freely implementable by any
// connector — even though it lives within the MPL-2.0 core tree. See LICENSING.md.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: event.proto

// Canonical Ajar event contract (ADR-0006).
//
// This .proto is the SOURCE OF TRUTH for the cross-language event/connector
// contract. Rust (prost), Go, and Python SDK types are generated from it so all
// stay byte-compatible. JSON is a debug/human projection only, never canonical.
// Canonical protobuf bytes are what gets signed for provenance and audit.
//
// Schema evolution follows proto3 rules: additive changes only, field numbers
// are reserved once retired, and `schema_version` is bumped for breaking shapes.
// Entity/field semantics align to MIP/JC3IEDM where a concept exists (ADR-0012).

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A normalized event flowing through the Ajar aggregation plane.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contract version (e.g. "v1"). Distinct from per-deployment policy version.
	SchemaVersion string `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Globally unique event id (e.g. UUIDv7 for time-ordering).
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Originating connector/source identity (ties to SPIFFE id, ADR-0008).
	SourceId string `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// MIP/JC3IEDM-aligned entity type (drone, vessel, signal, facility, ...).
	EntityType string `protobuf:"bytes,4,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	// When the SOURCE observed the event (sender's clock — UNTRUSTED for
	// ordering). RFC 3339 / ISO 8601 UTC. See ADR-0016.
	Timestamp string `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// When AJAR ingested the event (authoritative for ordering). RFC 3339 UTC.
	// The audit chain and stream order follow this + a monotonic ingest sequence,
	// never the sender's `timestamp`. See ADR-0016.
	ReceivedAt string `protobuf:"bytes,10,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	// Optional geospatial position. Kept structured (not free-form) so PostGIS
	// correlation (ADR-0005) can index it.
	Location *GeoPoint `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	// Connector-specific structured payload. Opaque to the core; validated by the
	// connector's declared standard mapping.
	Payload []byte `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	// Policy tags driving access/routing/cuing decisions (ADR-0003).
	PolicyTags []string `protobuf:"bytes,8,rep,name=policy_tags,json=policyTags,proto3" json:"policy_tags,omitempty"`
	// Detection/correlation confidence in [0.0, 1.0], if applicable.
	Confidence float64 `protobuf:"fixed64,9,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Type-specific structured attributes (ADR-0018/0022), validated against the
	// entity type's signed attribute schema. MUST be sorted by `key` with unique
	// keys so the canonical encoding stays byte-stable (the boundary rejects any
	// event whose attributes are unsorted or duplicated). The connector normalises
	// values into each attribute's declared unit.
	Attributes []*Attribute `protobuf:"bytes,11,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// Ungoverned passthrough metadata (ADR-0030): the long tail of vendor-specific
	// fields a sovereign does NOT need to govern. Carried + audited as opaque,
	// surfaced to the C2, but NOT type-validated/correlated. Allowed only when the
	// entity type's signed ontology sets `allows_metadata`. MUST be sorted by `key`
	// with unique keys (byte-stable canonical encoding) — a `repeated`, not a `map`.
	Metadata      []*Attribute `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Event) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Event) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

func (x *Event) GetLocation() *GeoPoint {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetPolicyTags() []string {
	if x != nil {
		return x.PolicyTags
	}
	return nil
}

func (x *Event) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Event) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Event) GetMetadata() []*Attribute {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// One structured attribute (e.g. heading="225"). Values are carried as strings;
// the ontology checks they satisfy the declared datatype/unit/bounds.
type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Attribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GeoPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AltitudeM     float64                `protobuf:"fixed64,3,opt,name=altitude_m,json=altitudeM,proto3" json:"altitude_m,omitempty"` // metres above WGS84 ellipsoid; 0 if unknown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoPoint) Reset() {
	*x = GeoPoint{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPoint) ProtoMessage() {}

func (x *GeoPoint) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPoint.ProtoReflect.Descriptor instead.
func (*GeoPoint) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *GeoPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoPoint) GetAltitudeM() float64 {
	if x != nil {
		return x.AltitudeM
	}
	return 0
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\rajar.event.v1\"\xbb\x03\n" +
	"\x05Event\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x1f\n" +
	"\ventity_type\x18\x04 \x01(\tR\n" +
	"entityType\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x1f\n" +
	"\vreceived_at\x18\n" +
	" \x01(\tR\n" +
	"receivedAt\x123\n" +
	"\blocation\x18\x06 \x01(\v2\x17.ajar.event.v1.GeoPointR\blocation\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x1f\n" +
	"\vpolicy_tags\x18\b \x03(\tR\n" +
	"policyTags\x12\x1e\n" +
	"\n" +
	"confidence\x18\t \x01(\x01R\n" +
	"confidence\x128\n" +
	"\n" +
	"attributes\x18\v \x03(\v2\x18.ajar.event.v1.AttributeR\n" +
	"attributes\x124\n" +
	"\bmetadata\x18\f \x03(\v2\x18.ajar.event.v1.AttributeR\bmetadata\"3\n" +
	"\tAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"c\n" +
	"\bGeoPoint\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"altitude_m\x18\x03 \x01(\x01R\taltitudeMb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_event_proto_goTypes = []any{
	(*Event)(nil),     // 0: ajar.event.v1.Event
	(*Attribute)(nil), // 1: ajar.event.v1.Attribute
	(*GeoPoint)(nil),  // 2: ajar.event.v1.GeoPoint
}
var file_event_proto_depIdxs = []int32{
	2, // 0: ajar.event.v1.Event.location:type_name -> ajar.event.v1.GeoPoint
	1, // 1: ajar.event.v1.Event.attributes:type_name -> ajar.event.v1.Attribute
	1, // 2: ajar.event.v1.Event.metadata:type_name -> ajar.event.v1.Attribute
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
