#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Fails if any source file is missing an SPDX Apache-2.0 header. Apache-2.0 asks
# that derivative works keep clear licensing; this keeps every file self-describing.
set -euo pipefail
cd "$(dirname "$0")/.."

needle="SPDX-License-Identifier: Apache-2.0"
missing=0

# Source we author (skip target/ and the vendored contract). Generated files
# are exempt: protoc-gen-go ("Code generated ... DO NOT EDIT"), nanopb
# ("Automatically generated nanopb ..."), and protoc python ("Generated by the
# protocol buffer compiler").
while IFS= read -r -d '' f; do
  if head -n 3 "$f" | grep -qE "Code generated|Automatically generated nanopb|Generated by the protocol buffer compiler"; then
    continue
  fi
  if ! head -n 5 "$f" | grep -q "$needle"; then
    echo "missing SPDX header: $f" >&2
    missing=1
  fi
done < <(find rust go cpp python scripts -type f \
            \( -name '*.rs' -o -name '*.go' -o -name '*.sh' \
               -o -name '*.cpp' -o -name '*.hpp' -o -name '*.c' -o -name '*.h' -o -name '*.py' \) \
            -not -path '*/target/*' -not -path '*/build/*' -not -path 'cpp/vendor/*' \
            -not -path '*/.venv/*' -not -path '*/__pycache__/*' -print0)

if [ "$missing" -ne 0 ]; then
  echo "ERROR: add '// $needle' (or '# ...') to the files above." >&2
  exit 1
fi
echo "license headers OK"
